version: '3.1'

services:

  intact-backend:
    image: hicsail/intact-backend:main
    ports:
      - "1333:8000"
    environment:
      STUDY_URL_PREFIX: ${STUDY_URL_PREFIX}
      DB_NAME: ${DB_NAME}
      DB_CONNECTION_STR: ${DB_CONNECTION_STR}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CORS_FRONTEND_ORIGIN: ${CORS_FRONTEND_ORIGIN}

  mongo:
    image: mongo:8
    restart: always
    volumes:
      - intact-backend-mongo-data-staging:/data/db

  backup:
    image: offen/docker-volume-backup:v2.43.0
    restart: always
    environment:
      BACKUP_CRON_EXPRESSION: "50 7 * * *"
      BACKUP_RETENTION_DAYS: 120
      AWS_S3_BUCKET_NAME: sail-data-backups
      AWS_S3_PATH: intact-backend-mongo-data-staging
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - intact-backend-mongo-data-staging:/backup/intact-backend-mongo-data-staging:ro

volumes:
  intact-backend-mongo-data-staging:
    external: true
