version: '3.1'

services:

  intact-backend:
    image: hicsail/intact-backend:main
    ports:
      - "1333:80"
    environment:
      HOSTNAME: ${HOSTNAME}
      DB_NAME: ${DB_NAME}
      DB_CONNECTION_STR: ${DB_CONNECTION_STR}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

  mongo:
    image: mongo:8
    restart: always
    volumes:
      - intact-backend-mongo-data-staging:/data/db

volumes:
  intact-backend-mongo-data-staging:
    external: true
